type = "service_account"
project_id = "api-drive-444401"
private_key_id = "d5a4a26b2be3cfeeee5185ae20aa26807f4dad6d"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC97SBmsWmIjGI8
1OuUauEAkdWRc05dM3eQxbyWPyi1C0yxsmbTBTJY9YaQQ2MAtsbefIVD2sDWf9xj
Q2JwDe9jw3C5BjgJwTYCpMM+Wp4N/AnaBqTqlfVdKCGBq2Q1YcJdo3UqoZ5HSWTG
HTGZGD06E3ho78DWMF329qMug0JFHZIloWBEEf8ZA/OWjBLfHnzbEOY+8zbuhsrL
2kEPlUJkhsZnqrL80L3iuZSspdSav2iXJuQinH5fPa0TwfUDsF5QcK6YPi6KHEss
7nyrkGh49XnACLvUQEJUHnJLEL+ymZ7JeyORcbgB+IpTwmdoVPX4Pzmx1+O2YQlE
TRbCeO1rAgMBAAECggEAL0bLBXUNEYXsYDsaByBRsNwcXu/mZlHM5fcqufWv0t0k
sqj3anjFLxqy688yYjedKj2xyJG35cz/FaBs7PqzB9DbCtuO8HKtWJwd07Qn2tBN
vX1g6Nn6MT2vlYEN2THj+X4aSMnhRdpxoNUchwDfIMk+9FQV2ttAUJzVQts+kEhd
hNULNNJJAB+0iRF4sp/3UAvRy0+MIYN4+WiKjOQY+gsLyPfs4wrknTR+/9RwyePk
VqEpPo8CBihxTOyGKlj8jOipmh6XMwmk6nL5yDSEhvoJGndySK4P38437TqVvzBr
b4KeWKY/tz9cllUQ50yvi5dFNId5SR3cyI3cu3Vf8QKBgQDt2lJOlEfojwu8ieWu
bz0MV38g7yTL7tO7Wt7KrXNwwL1wn7lvEYJSmmiazKNIVHe87LL1K/mPanRUxp7n
mYgNhh2Ne1/gM0ahybeVL6uoH3vgaQchcJxvc9tUQCBJOeHPfCypgzb5Qp6GjGKX
0UXxv8CFoVK/adEhcCvjDg3EkQKBgQDMardqeiMFN0BFycq3Yt5zeMda+iayejGU
3G3CdDMhPOfqJ1N+tDCVysA3mLI7U8nUIPB0owHNINwHDCou6ZIPrwY0VOlFJDB/
otlvmRu7/LEkM/bNfWzYGIq+A14TUGS5R1OsWpBzsrHDGVl/sZXhZwi05j3agusw
yNQrtFKgOwKBgQCEzn9gktjn2F9UQab2U/RBXOWGDSF9oPemSCHYBytLDMN6DCUt
CBi9aKv5q0OMkmVdHsj5rjklQ+p6n4CAjrBx5K3Bnt60v8yzb39LFJgDQrkXX210
1Xzzmjwf+cJNQL197ba+W56pZPJA7EfsvxQP3OJxetdKO5pi0lAe8mzrkQKBgQCy
lmk3tQzzeZnFXs6j+NSvvU0txm4Yb3jxvMKHqE0jNLrIbyMbBwGLXF8iM11DR6iE
k2KABAmG1LZl0dLouVbKLPcWsTg7F6rnV7bvMKxySAnavytXy8RT5t0PtJFz/kCB
Pjdz1ItvCScUdAkk7lkrW4DXym8vgEFJlasHo7qsEQKBgExyyp5j1oYy7vYF40yP
+XFgFIGrkgyNZQr1I8fCXFp6ifGA9DIASFzGsNCYkNRYwVDBSxGdIpw9vyR/W6Sp
2Cm+yVnpBFxDgNL2QIs1Q3ysJF/aeM+1neozVJ5V79hMbUAqMs151ISWsuAzPBU6
nFf3XTmseIbaa+39ShGSPQ2K
-----END PRIVATE KEY-----
"""
client_email = "streamlit-api@api-drive-444401.iam.gserviceaccount.com"
client_id = "115548780608226795855"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-api%40api-drive-444401.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
